def mainMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|  ______     __   __     ______     __     __   __     ______     ______     ______     __     __   __     ______        ______     ______   ______    |")
    print("| /\\  ___\\   /\\ \"-.\\ \\   /\\  ___\\   /\\ \\   /\\ \"-.\\ \\   /\\  ___\\   /\\  ___\\   /\\  == \\   /\\ \\   /\\ \"-.\\ \\   /\\  ___\\      /\\  == \\   /\\  == \\ /\\  ___\\   |")
    print("| \\ \\  __\\   \\ \\ \\-.  \\  \\ \\ \\__ \\  \\ \\ \\  \\ \\ \\-.  \\  \\ \\  __\\   \\ \\  __\\   \\ \\  __<   \\ \\ \\  \\ \\ \\-.  \\  \\ \\ \\__ \\     \\ \\  __<   \\ \\  _-/ \\ \\ \\__ \\  |")
    print("|  \\ \\_____\\  \\ \\_\\\\\"\\_\\  \\ \\_____\\  \\ \\_\\  \\ \\_\\\\\"\\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_\\  \\ \\_\\\\\"\\_\\  \\ \\_____\\     \\ \\_\\ \\_\\  \\ \\_\\    \\ \\_____\\ |")
    print("|   \\/_____/   \\/_/ \\/_/   \\/_____/   \\/_/   \\/_/ \\/_/   \\/_____/   \\/_____/   \\/_/ /_/   \\/_/   \\/_/ \\/_/   \\/_____/      \\/_/ /_/   \\/_/     \\/_____/ |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                             ___      _    _____ __    _____ __ __                         ___    _    _____ _____ _____ _____                         |")
    print("|                            |_  |    |_|  |  _  |  |  |  _  |  |  |                       |_  |  |_|  |     |  |  |     |_   _|                        |")
    print("|                             _| |_    _   |   __|  |__|     |_   _|                       |  _|   _   |  |  |  |  |-   -| | |                          |")
    print("|                            |_____|  |_|  |__|  |_____|__|__| |_|                         |___|  |_|  |__  _|_____|_____| |_|                          |")
    print("|                                                                                                         |__|                                          |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def nameMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                             _____ _____ _____ _____ _____    __ __ _____ _____ _____    _____ _____ _____ _____    _                                  |")
    print("|                            |   __|   | |_   _|   __| __  |  |  |  |     |  |  | __  |  |   | |  _  |     |   __|  |_|                                 |")
    print("|                            |   __| | | | | | |   __|    -|  |_   _|  |  |  |  |    -|  | | | |     | | | |   __|   _                                  |")
    print("|                            |_____|_|___| |_| |_____|__|__|    |_| |_____|_____|__|__|  |_|___|__|__|_|_|_|_____|  |_|                                 |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def classMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")    
    print("|                                                                                                                 __                                    |")
    print("|                             _____ _____ _____ _____    __ __ _____ _____ _____    _____ __    _____ _____ _____|  |                                   |")
    print("|                            |  _  |     |     |  |  |  |  |  |     |  |  | __  |  |     |  |  |  _  |   __|   __|  |                                   |")
    print("|                            |   __|-   -|   --|    -|  |_   _|  |  |  |  |    -|  |   --|  |__|     |__   |__   |__|                                   |")
    print("|                            |__|  |_____|_____|__|__|    |_| |_____|_____|__|__|  |_____|_____|__|__|_____|_____|__|                                   |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                  1: BIOMEDICAL                                                                        |")
    print("|                                                                  2: CHEMICAL                                                                          |")
    print("|                                                                  3: COMPUTER SCIENCE                                                                  |")
    print("|                                                                  4: ELECTRICAL/COMPUTER                                                               |")
    print("|                                                                  5: MECHANICAL                                                                        |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def firstMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("| "playerName + "has recently transferred to VCU from their hometown community college. As a way to get accostomed to the new envirnoment"
    print("| "playerName + "saw it best to spend some time in Monroe Park. Sitting next to the sprinkling fountain, he could hear birds, people, and revving car 
    print("| engines nearby. \"Wow, what a beautiful day!\" + playerName + though to himself. \"I'm feeling lucky!\" + playerName + flips a coin into the fountain, lodging itself into a crevase located at the top of the fountain. It is getting late and + playerName + decides to go home. + playerName + is suddenly startled and realizes there is a phantom like figure looking down over him! \"I am thou, thou art I. Thou hast acquired a new vow. It shall become the wings of rebellion that breakth thy chains of captivity. With the birth of the magic arcana, I have obtained the winds of blessing that should lead to freedom and new power...\" says the phantom figure right before he rushes into + playerName + 's body, coexisting with him. With this new power imbued within themself, our hero realizes their duty... to stop other students from suffering from pulling all nighters to complete coding assignments!! + playerName + sets foot first thing in the morning to finish this evil once and for all...")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")