def mainMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|  ______     __   __     ______     __     __   __     ______     ______     ______     __     __   __     ______        ______     ______   ______    |")
    print("| /\\  ___\\   /\\ \"-.\\ \\   /\\  ___\\   /\\ \\   /\\ \"-.\\ \\   /\\  ___\\   /\\  ___\\   /\\  == \\   /\\ \\   /\\ \"-.\\ \\   /\\  ___\\      /\\  == \\   /\\  == \\ /\\  ___\\   |")
    print("| \\ \\  __\\   \\ \\ \\-.  \\  \\ \\ \\__ \\  \\ \\ \\  \\ \\ \\-.  \\  \\ \\  __\\   \\ \\  __\\   \\ \\  __<   \\ \\ \\  \\ \\ \\-.  \\  \\ \\ \\__ \\     \\ \\  __<   \\ \\  _-/ \\ \\ \\__ \\  |")
    print("|  \\ \\_____\\  \\ \\_\\\\\"\\_\\  \\ \\_____\\  \\ \\_\\  \\ \\_\\\\\"\\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\ \\_\\  \\ \\_\\  \\ \\_\\\\\"\\_\\  \\ \\_____\\     \\ \\_\\ \\_\\  \\ \\_\\    \\ \\_____\\ |")
    print("|   \\/_____/   \\/_/ \\/_/   \\/_____/   \\/_/   \\/_/ \\/_/   \\/_____/   \\/_____/   \\/_/ /_/   \\/_/   \\/_/ \\/_/   \\/_____/      \\/_/ /_/   \\/_/     \\/_____/ |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                             ___      _    _____ __    _____ __ __                         ___    _    _____ _____ _____ _____                         |")
    print("|                            |_  |    |_|  |  _  |  |  |  _  |  |  |                       |_  |  |_|  |     |  |  |     |_   _|                        |")
    print("|                             _| |_    _   |   __|  |__|     |_   _|                       |  _|   _   |  |  |  |  |-   -| | |                          |")
    print("|                            |_____|  |_|  |__|  |_____|__|__| |_|                         |___|  |_|  |__  _|_____|_____| |_|                          |")
    print("|                                                                                                         |__|                                          |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("| DISCLAIMER: THIS STORY IS A WORK OF FICTION. SIMILARITIES BETWEEN CHARACTERS OR EVENTS TO PERSONS LIVING OR DEAD IN YOUR WORLD ARE PURELY COINCIDENTAL|")
    print("|                        BY PRESSING PLAY, YOU HAVE AGREED TO THE ABOVE, THEREFORE POSSESSING THE PRIVELDGE OF PARTAKING IN THIS GAME.                  |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def nameMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                             _____ _____ _____ _____ _____    __ __ _____ _____ _____    _____ _____ _____ _____    _                                  |")
    print("|                            |   __|   | |_   _|   __| __  |  |  |  |     |  |  | __  |  |   | |  _  |     |   __|  |_|                                 |")
    print("|                            |   __| | | | | | |   __|    -|  |_   _|  |  |  |  |    -|  | | | |     | | | |   __|   _                                  |")
    print("|                            |_____|_|___| |_| |_____|__|__|    |_| |_____|_____|__|__|  |_|___|__|__|_|_|_|_____|  |_|                                 |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def classMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")    
    print("|                                                                                                                 __                                    |")
    print("|                             _____ _____ _____ _____    __ __ _____ _____ _____    _____ __    _____ _____ _____|  |                                   |")
    print("|                            |  _  |     |     |  |  |  |  |  |     |  |  | __  |  |     |  |  |  _  |   __|   __|  |                                   |")
    print("|                            |   __|-   -|   --|    -|  |_   _|  |  |  |  |    -|  |   --|  |__|     |__   |__   |__|                                   |")
    print("|                            |__|  |_____|_____|__|__|    |_| |_____|_____|__|__|  |_____|_____|__|__|_____|_____|__|                                   |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                  1: BIOMEDICAL                                                                        |")
    print("|                                                                  2: CHEMICAL                                                                          |")
    print("|                                                                  3: COMPUTER SCIENCE                                                                  |")
    print("|                                                                  4: ELECTRICAL/COMPUTER                                                               |")
    print("|                                                                  5: MECHANICAL                                                                        |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def firstMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                          ,_                                           |")
    print("|                                                                                                            :`.            .--._                       |")
    print("|                                                                                                             `.`-.        /  ',-\"\"\"\"' tweet            |")
    print("|                                                                                                                `. ``~-._.'_.\"/    tweet               |")
    print("|                                                                                                                  `~-._ .` `~;                         |")
    print("|                                                                                                                      ;.    /                          |")
    print("|                                                                                                                     /     /                           |")
    print("|                                                                                                            jgs ,_.-';_,.'`                            |")
    print("|                                                                                                                `\"-;`/                                 |")
    print("|                                                                                                                 ,'`                                   |")
    print("|               ////^\\\\\\\\                                                                                                                               |")
    print("|               | ^   ^ |                                                                                                                               |")
    print("|              @ (o) (o) @                                                                                                                              |")
    print("|               |   <   |                                                                                                                               |")
    print("|               |  ___  |                                                                                                                               |")
    print("|                \_____/                                                                                                                                |")
    print("|              ____|  |____                                                                                                                             |")
    print("|             /    \__/    \                                                                                                                            |")
    print("|            /              \                                                                                                                           |")
    print("|           /\_/|        |\_/\                                                                                                                          |")
    print("|          / /  |        |  \ \                                                    ___________________                                                  |")
    print("|         ( <   |        |   > )                                                //|           |        \                                                |")
    print("|          \ \  |        |  / /                                               //  |           |          \                                              |")
    print("|           \ \ |________| / /                                  ___________//____|___________|__________()\__________________                           |")
    print("|            \ \| | | | |                               E=    /__________________|_=_________|_=___________|_________________{}                         |")
    print("|                 | | | |          E=                        [           ______ |           | .           | ==  ______      { }                         |")
    print("|                 | | | |                        VROOOOOOM __[__        /##  ##\|           |             |    /##  ##\    _{# }_                       |")
    print("|                 | | | |                     E=          {_____)______|##    ##|___________|_____________|___|##    ##|__(______}                      |")
    print("|                 | | | |                                             /  ##__##                              /  ##__##        \                         |")
    print("|---------------- | | | |-------------------------------------------------------------------------------------------------------------------------------|")
    print("|                 | | | |            \|/                                                                     \|/                                        |")
    print("|                 | | | |                                \|/                   \|/                                                                      |")
    print("|                  MM  MM                                                                                                                               |")
    print("|       \|/                                                                                                                                             |")
    print("|                                                                                                                            \|/                        |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("| Our hero has recently transferred to VCU from their hometown community college. As a way to get accostomed to the new envirnoment.                    |")
    print("| Our hero saw it best to spend some time in Monroe Park. Sitting next to the sprinkling fountain, they could hear birds, people, and revving car       |")
    print("| engines nearby. \"Wow, what a beautiful day!\" our hero though to themself. \"I'm feeling lucky!\"                                                        |")
    print("| Our hero flips a coin into the fountain, lodging itself into a crevase located at the top of the fountain. It is getting late and                     |")
    print("| Our hero decides to go home. Our hero is suddenly startled and realizes there is a phantom like figure looking down over him!                         |")
    print("| \"I am thou, thou art I. Thou hast acquired a new vow. It shall become the wings of rebellion that breakth thy chains of captivity.                    |")
    print("| With the birth of the magic arcana, I have obtained the winds of blessing that should lead to freedom and new power...\" says the phantom figure       |")
    print("| right before he rushes into our hero's body, coexisting with him. With this new power imbued within themself, our hero realizes their duty...         |")
    print("| to stop other students from suffering from pulling all nighters to complete coding assignments!! Our hero sets foot first thing                       |")
    print("| in the morning to finish this evil once and for all...                                                                                                |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def secondMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                 /////////////\\\\\\\\                                                                                     |")
    print("|                                                (((((((((((((( \\\\\\\\                                                                                    |")
    print("|                                                ))) ~~      ~~  (((                                                                                    |")
    print("|                                                ((( (*)     (*) )))                                                                                    |")
    print("|                                                )))     <       (((             um actually                                                            |")
    print("|                                                ((( '\\______/`  )))                                                                                    |")
    print("|                                                )))\\___________/(((                                                                                    |")
    print("|                                                       _) (_                                                                                           |")
    print("|                                                      / \\_/ \\                                                                                          |")
    print("|                                                     /(     )\\                                                                                         |")
    print("|                                                    // )___( \\\\                                                                                        |")
    print("|                                                    \\\\(     )//                                                                                        |")
    print("|                                                     (       )                                                                                         |")
    print("|                                                      |  |  |                                                                                          |")
    print("|                                                       | | |                                                                                           |")
    print("|                                                       | | |                                                                                           |")
    print("|                                                      _|_|_|_                                                                                          |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("| On his way to the engineering building, he encounters an annoying student! He won't stop flexing how good his job is and so he must be stopped...     |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def thirdMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                              ,                                                                        |")
    print("|                                                                           ,:' `..;                                                                    |") 
    print("|                                                                           `. ,;;'%                                                                    |")
    print("|                                                                           +;;'%%%%%                                                                   |")
    print("|                                                                            /- \%,)%%                                                                  |")
    print("|                                                                            `   \\ %%                                                                   |")
    print("|                                          house keeping!                     =  )/ \\                                                                   |")
    print("|                                                                             `-'/ / \\                                                                  |")
    print("|                                                                             _/\\/.-.\\                                                                  |")
    print("|                                                                            |  (    |                                                                  |")
    print("|                                                                            |  |   ||                                                                  |")
    print("|                                                                            |  |   ||                                                                  |")
    print("|                                                                        _.-----'   ||                                                                  |")
    print("|                                                                      / \\________,' |                                                                  |")
    print("|                                                                      (((/  |       |                                                                  |")
    print("|                                                                      //    |       |                                                                  |")
    print("|                                                                     //     |\\      |                                                                  |")
    print("|                                                                    //      | \\     |                                                                  |")
    print("|                                                                   //       |  \\    |                                                                  |")
    print("|                                                                  //        |   \\   |                                                                  |")
    print("|                                                                 //         |    \\  |                                                                  |")
    print("|                                                                //          |    |\\ |                                                                  |")
    print("|                                                               //           |    | \\|                                                                  |")
    print("|                                                              //            \    \                                                                     |")
    print("|                                                             c'             |\\    \                                                                    |")
    print("|                                                                            | \\    \\                                                                   |")
    print("|                                                                            |  \\    \\                                                                  |")
    print("|                                                                            |.' \\    \\                                                                 |")
    print("|                                                                           _\\    \\.-' \\                                                                |")
    print("|                                                                          (___.-(__.'\\/                                                                |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("| Our hero is now in the engineering building. Our hero needs to use the bathroom before taking on the final villain.                                   |")
    print("| Unfortunately, there is a janitor blocking the path saying it must be cleaned!                                                                        |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def fourthMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                             .            .--.                                                                         |")
    print("|                                                             \\\\          //\\\\ \                                                                        |")
    print("|                                                             .\\\\        ///_\\\\\\\\                                                                       |")
    print("|                                                             :/>`      /(| `|'\\\\\\                                                                      |")
    print("|                                                             Y/\\      )))\\_-_/((\\                                                                      |")
    print("|                                                              \\ \\    ./'_/ \" \\_`\\)                                                                     |")
    print("|                                                               \\ \\.-\" ._ \\   /   \\                                                                     |")
    print("|                           your funds are mine!                 \\ _.-\" (_ \\Y/ _) |                                                                     |")
    print("|                                                                 \"      )\" | \"\"/||                                                                     |")
    print("|                                                                     .-'  .'  / ||                                                                     |")
    print("|                                                                    /    `   /  ||                                                                     |")
    print("|                                                                   |    __  :   ||_                                                                    |")
    print("|                                                                   |   / \\   \\ '|\\`                                                                    |")
    print("|                                                                   |  |   \\   \\                                                                        |")
    print("|                                                                   |  |    `.  \\                                                                       |")
    print("|                                                                   |  |      \\  \\                                                                      |")
    print("|                                                                   |  |       \\  \\                                                                     |")
    print("|                                                                   |  |        \\  \\                                                                    |")
    print("|                                                                   |  |         \\  \\                                                                   |")
    print("|                                                                   /__\\          |__\\                                                                  |")
    print("|                                                                   /.|            |.\\_                                                                 |")
    print("|                                                                   `-''            ``--'                                                               |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("| As the hero approaches closer and closer to his lair, our hero is stopped by an academic advisor!                                                     |")
    print("| She mentions we have a hold on our account for not paying semester dues! \"hah, no worries.. I'll just pay with these hands!\")                         |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def fifthMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("| With everyone out of the way, we have arrived at the villian's lair. \"It is time to settle this once and for all!\" Our hero rushes into his office.   |")
    print("| \"I've been expecting you...\" If you want no more coding assignments, you'll have to defeat me!                                                        |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def miniBossFight(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         ANNOYING STUDENT:                          |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def miniBossFight2(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         JANITOR:                          |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def miniBossFight3(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         ACADEMIC ADVISOR:                          |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def miniBossFight4(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         KLENKE:                                    |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def miniBossFight5(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         MOTAI:                                     |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")    

def miniBossFight6(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         RESLER:                                    |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def miniBossFight7(playerHP,miniBossHP,playerLevel):
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                   1 : ATTACK                                                                          |")
    print("|-------------------------------------------------------------------------------------------------------------------------------------------------------|")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|    YOUR CHARACTER:                                                                                         GHOSH:                                     |")
    print("|    LEVEL: ",playerLevel,"                                                                                      HP: [",miniBossHP,"/250]                                     |")
    print("|    HP: [",playerHP,"/100]                                                                                                                                     |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def lostToMiniBoss():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                     ______   _______  _______  _______  _______  _______  _______  ______                                             |")
    print("|                                    |      | |       ||       ||       ||   _   ||       ||       ||      |                                            |")
    print("|                                    |  _    ||    ___||    ___||    ___||  |_|  ||_     _||    ___||  _    |                                           |")
    print("|                                    | | |   ||   |___ |   |___ |   |___ |       |  |   |  |   |___ | | |   |                                           |")
    print("|                                    | |_|   ||    ___||    ___||    ___||       |  |   |  |    ___|| |_|   |                                           |")
    print("|                                    |       ||   |___ |   |    |   |___ |   _   |  |   |  |   |___ |       |                                           |")
    print("|                                    |______| |_______||___|    |_______||__| |__|  |___|  |_______||______|                                            |")                                                                                  
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def victoryMiniBoss():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                             __   __  ___   _______  _______  _______  ______    __   __                                               |")
    print("|                                            |  | |  ||   | |       ||       ||       ||    _ |  |  | |  |                                              |")
    print("|                                            |  |_|  ||   | |       ||_     _||   _   ||   | ||  |  |_|  |                                              |")
    print("|                                            |       ||   | |       |  |   |  |  | |  ||   |_||_ |       |                                              |")
    print("|                                            |       ||   | |      _|  |   |  |  |_|  ||    __  ||_     _|                                              |")
    print("|                                             |     | |   | |     |_   |   |  |       ||   |  | |  |   |                                                |")
    print("|                                              |___|  |___| |_______|  |___|  |_______||___|  |_|  |___|                                                |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def transitionMenu():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")

def enemyAttacked():
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("|                                                                 THE ENEMY HAS ATTACKED                                                                |")
    print("|                                                                                                                                                       |")
    print("|                                                                                                                                                       |")
    print("---------------------------------------------------------------------------------------------------------------------------------------------------------")